apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-appointment-api-deployment
  labels:
    app: doctor-appointment-api
spec:
  replicas: 1  # Number of pods
  selector:
    matchLabels:
      app: doctor-appointment-api
  template:
    metadata:
      labels:
        app: doctor-appointment-api
    spec:
      containers:
        - name: doctor-appointment-api
          image: abwshaf/doctor-appointment-api:latest # Replace with your image path
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-appointment-api-service
  labels:
    app: doctor-appointment-api
spec:
  type: LoadBalancer  # Exposes the service externally with a cloud provider's load balancer
  ports:
    - port: 80  # The port the external LB will listen on
      targetPort: 8080  # The container's port where the application is running
  selector:
    app: doctor-appointment-api
