name: BACKEND-CI

# Trigger the workflow when push to main
on:
    push:
        branches:
            - main

# Define the Jobs
jobs:
    build:

        # The OS which the pipeline will run
        runs-on: ubuntu-latest

        # Set Up MySQL Service
        services:
          mysql:
            image: mysql:8
            ports:
              - 3306:3306
            env:
              MYSQL_ROOT_PASSWORD: Shaf@123
              MYSQL_DATABASE: doctor_appointment
              MYSQL_USER: shafeeque
              MYSQL_PASSWORD: Shaf@123
            options: >-
              --health-cmd="mysqladmin ping --silent"
              --health-interval=10s
              --health-timeout=5s
              --health-retries=3

        # Define the steps in the build job
        steps:
            # step 1: Check out the code from the repo
            - name: Check out repository code
              uses: actions/checkout@v3

            # Step 2: Set up JDK 17
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: '17'

            # Step 3: Cache Maven dependencies
            - name: Cache Maven dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-
                      
            # Step 4: Build and test the application using Maven
            - name: Build with Maven
              run: mvn clean install test -Dspring.datasource.url=jdbc:mysql://localhost:3306/doctor_appointment \
                -Dspring.datasource.username=shafeeque \
                -Dspring.datasource.password=Shaf@123

