name: BACKEND-CI

# Trigger the workflow when push to main
on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  GKE_CLUSTER: gksdadev001
  GKE_ZONE: us-central1-c

# Define the Jobs
jobs:
    build:

        # The OS which the pipeline will run
        runs-on: ubuntu-latest

        # Set Up MySQL Service
        services:
          mysql:
            image: mysql:8
            ports:
              - 3306:3306
            env:
              MYSQL_ROOT_PASSWORD: Shaf@123
              MYSQL_DATABASE: doctor_appointment
              MYSQL_USER: shafeeque
              MYSQL_PASSWORD: Shaf@123
            options: >-
              --health-cmd="mysqladmin ping --silent"
              --health-interval=10s
              --health-timeout=5s
              --health-retries=3

        # Define the steps in the build job
        steps:
            # step 1: Check out the code from the repo
            - name: Check out repository code
              uses: actions/checkout@v3

            # Step 2: Set up JDK 17
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: '17'
                  server-id: docker.io
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD  

            # Step 3: Cache Maven dependencies
            - name: Cache Maven dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-
                      
            # Step 4: Build and test the application using Maven
            - name: Build and Test with Maven
              run: mvn clean install test

            # Step 5: Login to DockerHub
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            # Step 6: Build & Push to DockerHub
            - name: Build & Push to DockerHub
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  platforms: linux/amd64
                  tags: ${{ secrets.DOCKER_USERNAME }}/doctor-appointment-api:latest

    Deploy:
        needs: build

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master
            - name: kubectl - Google Cloud GKE cluster.
              uses: ameydev/gke-kubectl-action@master
              env:
                PROJECT_ID: ${{ env.PROJECT_ID }}
                APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}
                CLUSTER_NAME: ${{ env.GKE_CLUSTER }}
                ZONE_NAME: ${{ env.GKE_ZONE }}
              with:
                args: apply -f k8s/
