name: BACKEND-CI

# Trigger the workflow when push to main
on:
    push:
        branches:
            - main

# Define the Jobs
jobs:
    build:

        # The OS which the pipeline will run
        runs-on: ubuntu-latest

        # Define the steps in the build job
        steps:
            # step 1: Check out the code from the repo
            - name: Check out repository code
              uses: actions/checkout@v3

            # Step 2: Set up JDK 17
            - name: Set up JDK 17
              uses: actions/setup-java@4
              with:
                  distribution: 'zulu'
                  java-version: '17'

            # Step 3: Cache Maven dependencies
            - name: Cache Maven dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-
                      
            # Step 4: Build and test the application using Maven
            - name: Build with Maven
              run: mvn clean install -DskipTests

            # Step 5: Run tests
            - name: Run unit tests
              run: mvn test